openapi: 3.0.0
info:
  version: "1.0.0"
  title: API de Dominios
  description: Documentación de la API de Dominios de la materia 75.43 Introducción a Sistemas Distribuidos

servers:
  - url: http://localhost:8080/api
    description: Servidor de desarrollo

# Paths servidos por la aplicación
paths:
  /domains/{domain}:
    get:
      operationId: "api.dominios.getDomain"
      tags:
        - "Dominios"
      summary: "Obtiene la IP asociada a un dominio particular"
      description: "Obtiene la IP asociada a un dominio en particular, pudiendo ser este un custom domain
                    creado previamente. Si en hostname tiene varias IPs distintas, el servicio deberá devolver
                    sólo una. Sin embargo, ​ si se vuelve a pedir la IP de ese dominio​ , deberá irse alternando
                    entre las que provee el resolver de DNS en forma de ​ round robin."
      parameters:
        - in: path
          name: domain
          required: true
          schema:
            type: string
          description: Nombre del Dominio a obtener su IP asociada.
      responses:
        200:
          description: "Operación de lectura exitosa"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dominio'
        404:
          description: "El Dominio solicitado no se encuentra en sistema"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /custom-domains:
    post:
      operationId: "api.dominios.addDomain"
      tags:
        - "Dominios"
      summary: "Crea una entrada para sobreescribir la IP de un Dominio en particular"
      description: "Crea una entrada para sobreescribir la IP de un Dominio en particular."
      requestBody:
        required: true
        x-body-name: 'dominio'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InputDominio'
      responses:
        201:
          description: "Se creo el Domino correctamente"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dominio'
        400:
          description: "Dominio ya existente o cuerpo del Request mal formado"
    put:
        operationId: "api.dominios.modificar"
        tags:
          - "Dominios"
        summary: "Edita un Dominio ya existente en el sistema"
        description: "Edita un Dominio ya existente en el sistema."
        requestBody:
          required: true
          x-body-name: 'dominio'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InputDominio'
        responses:
          200:
            description: "El Dominio se actualizo correctamente"
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Dominio'
          404:
            description: "El Dominio solicitado no se encuentra en sistema"
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Error'
          400:
            description: "Cuerpo del Request mal formado"
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Error'
# Declaración de tipos de datos
components:
  schemas:
    Dominio:
      type: "object"
      properties:
        domain:
          type: "string"
        ip:
          type: "string"
        custom:
          type: "boolean"
    InputDominio:
      type: "object"
      properties:
        domain:
          type: "string"
        ip:
          type: "string"
    Error:
      type: "object"
      properties:
        error:
          type: "string"